# permissions for end users to view cucumbers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cucumber-viewer-role
rules:
- apiGroups:
  - caproven.info
  resources:
  - cucumbers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - caproven.info
  resources:
  - cucumbers/status
  verbs:
  - get
