# permissions for end users to view kappas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kappa-viewer-role
rules:
- apiGroups:
  - caproven.info
  resources:
  - kappas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - caproven.info
  resources:
  - kappas/status
  verbs:
  - get
